name: Python Movie Recommender API

on:
  push:
    branches: [ "api" ]
  pull_request:
    branches: [ "api" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker Image
      run: |
        docker build -t recapi .
    - name: Run Tests in Docker
      run: |
        docker run --rm recapi pytest /app
